// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Fruit struct {
	ID        int32
	Name      pgtype.Text
	Colour    pgtype.Text
	CreatedAt pgtype.Timestamp
}
