// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Fruit struct {
	ID        interface{}  `json:"id"`
	Name      string       `json:"name"`
	Colour    string       `json:"colour"`
	CreatedAt sql.NullTime `json:"created_at"`
}
